mysite/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, ListView
from mysite.views import BasicArithmeticForm
from mysite.models import Level, Worksheet

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^polls/', include('polls.urls')),
    url(r'^admin/', include(admin.site.urls)),
	url(r'^$', TemplateView.as_view(template_name='index.html'), name='mysite_home'),
    url(r'^(?i)about', TemplateView.as_view(template_name='about.html')),
    url(r'^(?i)contact', 'mysite.views.contact', name='contact.html'),
    url(r'^(?i)thankyou', TemplateView.as_view(template_name='contact_thankyou.html')),
	url(r'^(?i)addition/$', TemplateView.as_view(template_name='addition/index.html')),
	#url(r'^(?i)addition/basic',  'mysite.views.basicAddition' ),
    url(r'^(?i)worksheets',
        ListView.as_view(
            queryset=Worksheet.objects.all().order_by('worksheet_name', 'level'),
            context_object_name='worksheet_list',
            template_name='worksheets.html')),
	#url(r'^(?i)addition/some_view',  'mysite.views.some_view' ),
    #url(r'^(?i)addition/generatePDF/(?P<rows>\d+)/(?P<cols>\d+)/$',  'mysite.views.generatePDF', name='generatePDF' ),
    url(r'^(?i)generatePDFWorksheet/(?P<worksheet_id>\d+)/$',  'mysite.views.generatePDFWorksheet', name='generatePDFWorksheet' ),

    url(r'^register/', 'mysite.views.register', name='mysite_register'),
    url(r'^login_test/', 'mysite.views.login_test', name='mysite_login_test'),
)
urlpatterns += patterns('django.contrib.auth.views',
    url(r'^login/', 'login', {'template_name': 'login.html'}, name='mysite_login'),
    url(r'^logout/', 'logout', {'next_page': '/login'}, name='mysite_logout'),

)

polls/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import DetailView, ListView
from polls.models import Poll


#urlpatterns = patterns('polls.views',
#    url(r'^$', 'index'),
#    url(r'^(?P<poll_id>\d+)/$', 'detail'),
#    url(r'^(?P<poll_id>\d+)/results/$', 'results'),
#    url(r'^(?P<poll_id>\d+)/vote/$', 'vote'),
#	url(r'login/', 'login'),
#	url(r'logout/', 'logout'),
#)

urlpatterns = patterns('',
    url(r'^$',
        ListView.as_view(
            queryset=Poll.objects.order_by('-pub_date')[:5],
            context_object_name='latest_poll_list',
            template_name='polls/index.html')),
    url(r'^(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Poll,
            template_name='polls/detail.html')),
    url(r'^(?P<pk>\d+)/results/$',
        DetailView.as_view(
            model=Poll,
            template_name='polls/results.html'),
        name='poll_results'),
    url(r'^(?P<poll_id>\d+)/vote/$', 'polls.views.vote'),
)

mysite/models.py
import datetime
from django.utils import timezone
from django.db import models

from django import forms
import random

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


# Create your models here.

#class Poll(models.Model):
#    question = models.CharField(max_length=200)
#    pub_date = models.DateTimeField('date published')
#     def __str__(self):
#         return str(self.question)
#     def was_published_recently(self):
#         return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
#     was_published_recently.admin_order_field = 'pub_date'
#     was_published_recently.boolean = True
#     was_published_recently.short_description = 'Published recently?'
#
# class Choice(models.Model):
#     poll = models.ForeignKey(Poll)
#     choice = models.CharField(max_length=200)
#     votes = models.IntegerField()
#     def __str__(self):
#         return str(self.choice)

#====================================================================================
# business models
#====================================================================================

class Level(models.Model):
    level_name = models.CharField(max_length=5, primary_key=True)
    def get_level_name(self):
        return self.level_name



class Worksheet(models.Model):

    WORKSHEET_NAME_CHOICES = (
        ('Addition', 'Addition'),
        ('Subtraction', 'Subtraction'),
        ('Multiplication', 'Multiplication')
    )
    TEMPLATE_CHOICES = (
        ('TWOCOL', 'Two Columns, Single Line Operations'),
        ('THREECOL', 'Three Columns, Single Line Operations'),
        ('FOURCOL', 'Four Columns, Multiple Line Operations')
    )


    worksheet_name = models.CharField(max_length=20, choices=WORKSHEET_NAME_CHOICES)
    level = models.ForeignKey(Level)
    description = models.CharField(max_length=2000)
    number_of_exercises = models.IntegerField()
    average_time = models.IntegerField()


    min_int_1 = models.IntegerField()
    max_int_1 = models.IntegerField()
    min_int_2 = models.IntegerField()
    max_int_2 = models.IntegerField()

    worksheet_template = models.CharField(max_length=10, choices=TEMPLATE_CHOICES)

    def get_worksheet_name(self):
        return self.worksheet_name

    def getDifferentRandomTerm(self, term1, minInt, maxInt):
        newTerm = random.randint(minInt, maxInt)
        while (newTerm == term1):
            newTerm = random.randint(minInt, maxInt)
        return newTerm

    def getRandomInt(self, termName, minInt, maxInt, rules, rulesParams = {}):

        local_scope = {}

        local_scope['randomNumber'] = random.randint(minInt, maxInt)
        #local_scope['randomNumber'] = 12

        rulesParams[termName] = "local_scope['randomNumber']"
        #randomNumber = random.randint(minInt, maxInt)
        # the while loop is not very optimal, but is quite generic to find a proper term that meets the criteria intEval
        # also be careful with infinite loops (rules that cannot be satisfied)



        #exec("local_scope['randomNumber'] = (local_scope['randomNumber'] if local_scope['randomNumber'] % 10 > 6 else local_scope['randomNumber'] // 10 * 10 + ( 10 - local_scope['randomNumber'] % 4))", locals())


        for r in rules.all():
            statement = "local_scope['randomNumber'] = " + self.populateTags(r.rule, rulesParams)
            exec(statement, locals())

#        params = {"key1":"value1", "key2":"value2", "key3":"value3"}
#        originalString = "testing populated string k1: {{key1}}, k2: {{key2}}, k3: {{key3}}"
#        populatedString = self.populateTags(originalString, params)

#        while self.evalRules(randomNumber, rules.all(), rulesParams) == False:
#            randomNumber = random.randint(minInt, maxInt)
        return local_scope['randomNumber']

    def get_int_1_rules(self):
        # figure a BETTER WAY BETTER way to do this!!!!!!
        worksheet = Worksheet.objects.get(pk=self.id)
        return worksheet.worksheetint1rules_set

    def get_int_2_rules(self):
        # figure a BETTER WAY BETTER way to do this!!!!!!
        worksheet = Worksheet.objects.get(pk=self.id)
        return worksheet.worksheetint2rules_set

    def evalRules(self, randomNumber, rules, rulesParams):
        is_valid = True
        for r in rules.all():
            if eval(str(randomNumber) + r.rule) == False:
               is_valid = False
               break
        return  is_valid

    def populateTags(self, originalString, tagsDictionary):
        populatedString = originalString
        for k in tagsDictionary.keys():
            populatedString = populatedString.replace("{{" + k  + "}}", str(tagsDictionary[k]))
        return populatedString


class WorksheetInt1Rules(models.Model):
    worksheet = models.ForeignKey(Worksheet)
    rule = models.CharField(max_length=1000)

class WorksheetInt2Rules(models.Model):
    worksheet = models.ForeignKey(Worksheet)
    rule = models.CharField(max_length=1000)



########################################################################################################################################
#class DaysOfWeek(Enum):
#    Monday = 1
#    Tuesday = 2
#    Wednesday = 4
#    Thursday = 8

#DAYS_OF_WEEK = ((1, 'Monday'), (2, 'Tuesday'), (4, 'Wednesday'), (8, 'Thursday'), (16, 'Friday'), (32, 'Saturday'), (64, 'Sunday'))

#class Provider(models.Model):
#    name = models.CharField(max_length=30)
#    def __str__(self):
#        return str(self.name)
#    def get_blocked_days_of_week(self):
#        return

#class DaysOfWeekSlot(models.Model):
#    provider = models.ForeignKey(Provider)
#    weekday = models.IntegerField(choices=DAYS_OF_WEEK)
#    time = models.TimeField()
#    class Meta:
#        unique_together = (("provider", "weekday", "time"),)
#    def __str__(self):
#        return "%s - %s - %s" % (str(self.provider), str(self.weekday), str(self.time))

#class CalendarDaySlot(models.Model):
#    provider = models.ForeignKey(Provider)
#    date = models.DateField()
#    time = models.TimeField()
#    class Meta:
#        unique_together = (("provider", "date", "time"),)
#    def __str__(self):
#        return "%s - %s - %s" % (str(self.provider), str(self.date), str(self.time))






#====================================================================================
# form models
#====================================================================================
class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Enter Subject'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'rows': '25', 'cols': '80', 'class': 'form-control', 'placeholder':'Enter Your Message'}))
    sender = forms.EmailField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter Email'}))
    cc_myself = forms.BooleanField(required=False)


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields = ("username", "email")

    def clean_email(self):
        return self.cleaned_data.get('email')
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

templates/about.html
{% extends "framed.html" %}

{% load staticfiles %}

{% block title %} Addition {% endblock title %}

{% block framedcontent %}

    <div class="border padded_border">
        <div class="section_header">
            <h3>About</h3>
        </div>
        <div>
            <p>How long does your kid take to answer 8 + 7? Does he still use his finguers? How about 99 + 99?</p>

            <p>

                Automatic recall of basic math facts (math fluency) is generally considered a key foundation for higher
                level math skills.
            </p>

            <p>
                My kids can add and subtract multiple digits, but we still do single digits addition math drills. Why? Because the goal is not to teach them Math. They already understand the concept. The goal is to make them fluent in Math.
                I want Math to be like a second language for them. To achieve that, they need to be able to automatically recall basic math facts, without using fingers or spending much time on them. They also need to understand there are often different ways to solve the same Math problem, and to learn shortcuts.
            </p>

            <h6>Shortcuts</h6>

            <p>
                How do your kids solve 99 + 99? Do they write it down on a piece of paper, then add the single column, figure out the carry and add the tens column?
                I want my kids to solve it by figuring out that 99 = 100 - 1, so 99 + 99 = 100 + 100 - 2.
                The more Math facts they're able to automatically recall, the more shortcuts they'll be able to find by themselves.

            </p>
            <h6>Timed</h6>

            <p>

                These worksheets should be timed. It's important to let your kids know that they'll need both speed and accuracy. They often ask me, which one is more important. I tell them they're equally important.
                It's just as bad to take an hour to solve one worksheet perfectly as it is to solve the worksheet in 2 minutes, but get half of it wrong.

            </p>

            <h6>Worksheets</h6>

            <p>
                I organized worksheets by operation types and level. As they get comfortable with a level, I create a new level and have them practice it. The progression is quite disorganized and not really planned. I simply create the worksheets as I need them.
            </p>

            <p>
                Why print the worksheets and not have the kids practice online on a computer? The goal is to measure their progress and make them proficient in Math. Speed (as well as accuracy) is key and I believe doing it on a piece of paper with a pencil to be much faster than doing it on a keyboard/mouse.
            </p>
            <p>Go <a href="/worksheets">check them now!</a></p>

            <h6>Servers</h6>
            <p>The site is a bit slow, because it's hosted on a free virtual instance on Heroku. If you start having problems accesing the site, let me know and I'll look into upgrading the hosting. So far the site has only been for personal purposes, so it would only get a few dozen visits a week.</p>

            <h6>Work in progress</h6>

            <p>I know the site design has nothing to do with Math. That's because I simply purchased a template and used it and did not yet find suitable images for the site.</p>

            <h6>Contact Us</h6>
            <p>I would love <a href="/contact">to hear suggestions</a> for new worksheets and what you think of this site.</p>
        </div>


    </div>
    </div>
{% endblock framedcontent %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load staticfiles %}
    <title>{% block title %}templates/base.html{% endblock %}</title>
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,700' rel='stylesheet' type='text/css'>


    <link href="{% static "bootstrap-3.1.1-dist/css/bootstrap.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "content/StyleSheet.css" %}" rel="stylesheet" type="text/css"/>
	<link href="{% static "content/css/theme.css" %}" rel="stylesheet" type="text/css"/>
	<link href="{% static "content/css/index.css" %}" rel="stylesheet" type="text/css"/>
	<link href="{% static "content/css/lib/animate.css" %}" rel="stylesheet" type="text/css"/>

	



	<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.3.js" type="text/javascript"></script>
    <script src="{% static "bootstrap-3.1.1-dist/js/bootstrap.min.js" %}" type="text/javascript"></script>
	<script src="{% static "scripts/theme.js" %}" type="text/javascript"></script>

	
	
	
	{% block header %} {% endblock header %}
</head>
<body>


<body class="pull_top">
    <div class="navbar transparent navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
            <a class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="navbar-brand brand" href="/">
                <strong>MATHIMIZE</strong>
            </a>
            <div class="collapse navbar-collapse navHeaderCollapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/" class="active">HOME</a></li>
                    <li><a href="/about">ABOUT</a></li>
                    <li><a href="/worksheets">WORKSHEETS</a></li>
                    <!--
                    <li class="dropdown">
                        
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Addition
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/Addition/">Guide</a></li>
                            <li class="divider"></li>
                            <li><a href="/Addition/Tens">Tens</a></li>
                            <li><a href="/Addition/Doubles">Doubles</a></li>
                            <li><a href="/Addition/BasicAddition">Basic Addition</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Subtraction
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Tens</a></li>
                            <li><a href="#">Doubles</a></li>
                            <li><a href="#">BasicAddition</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Time
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/Time/OClocks">OClocks</a></li>
                            <li><a href="/Time/Halves">Halves</a></li>
                            <li><a href="/Time/Quarters">Quarters</a></li>
                            <li><a href="/Time/QuartersText">Quarters Text</a></li>
                            <li><a href="/Time/TellTime">Tell the time</a></li>
                        </ul>
                    </li>
                    -->
                    <li><a href="/contact">CONTACT US</a></li>
                </ul>
            </div>
        </div>
      </div>
	</div>
	
	
	{% block content %} {% endblock content %}
	
	
	
    <!-- starts footer -->
    <footer id="footer">
        <div class="container">
            <div class="row info">
                <div class="span6 residence">
                    <ul>
                    </ul>
                </div>
                <div class="span5 touch">
                    <ul>
                        <li><strong>E.</strong><a href="#"> admin@mathimize.com</a></li>
                    </ul>
                </div>
            </div>     
            <div class="row credits">
                <div class="span12">
                    <div class="row social">
                        <div class="span12">
                            <a href="http://facebook.com/mathimize" class="facebook">
                                <span class="socialicons ico1"></span>
                                <span class="socialicons_h ico1h"></span>
                            </a>
                            <a href="#" class="twitter">
                                <span class="socialicons ico2"></span>
                                <span class="socialicons_h ico2h"></span>
                            </a>
                        </div>
                    </div>
                    <div class="row copyright">
                        <div class="span12">
                            @ 2013 Mathimize. All rights reserved.
                        </div>
                    </div>
                </div>            
            </div>
        </div>
    </footer>

	
	
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-325815-8']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>


</body>
</html>

templates/contact.html
{% extends "framed.html" %}

{% load staticfiles %}

{% block title %} Contact Us {% endblock title %}

{% block header %}
    <style>
    /*
        #id_message{
            width: 650px;
        }
    */
    .errorlist{
        color: #ff0000;
    }

    </style>

 {% endblock header %}

{% block framedcontent %}

    <div class="border padded_border">
	    <div class="section_header">
			<h3>Contact Us</h3>
		</div>
        <form method="post" role="form" class="form-horizontal">{% csrf_token %}

            {{ form.non_field_errors }}
                <div class="form-group">
                    {{ form.sender.errors }}
                    <label for="id_sender" class="col-sm-2 control-label">Email address:</label>
                    <div class="col-sm-10">
                        {{ form.sender }}
                    </div>
                </div>
                <div class="form-group">
                    {{ form.subject.errors }}
                    <label for="id_subject" class="col-sm-2 control-label">Subject:</label>
                    <div class="col-sm-10">
                    {{ form.subject }}
                        </div>
                </div>
                <div class="form-group">
                    {{ form.message.errors }}
                    <label for="id_message" class="col-sm-2 control-label">Your message:</label>
                    <div class="col-sm-10">
                    {{ form.message }}
                        </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-12">
                        <p class="pull-right"><input type="submit" value="Send Email" class="btn btn-primary"></p>
                    </div>
                </div>


        </form>
    </div>
{% endblock framedcontent %}

templates/contact_thankyou.html
{% extends "framed.html" %}

{% load staticfiles %}

{% block title %} Contact Us {% endblock title %}

{% block framedcontent %}

    <div class="border padded_border">
	    <div class="section_header">
			<h3>Contact Us</h3>
		</div>
        <p>Thank You for your message.
        </p>
        <p>Check our worksheets <a href="/worksheets">here</a></p>

    </div>
{% endblock framedcontent %}

templates/framed.html
{% extends "base.html" %}

{% block content %}
    <div id="mathimize_body" class="container">
        <div class="row">
            <div class="span12">
                {% block framedcontent %} {% endblock framedcontent %}
            </div>
        </div>
    </div>

{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} Mathimize {% endblock title %}

{% block header %}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#getStarted").click(function () {
                window.location = "/Addition";
            });
        });
    </script>
{% endblock header %}	

{% block content %}
    <section id="feature_slider" class="">
        <!-- 
            Each slide is composed by <img> and .info
            - .info's position is customized with css in index.css
            - each <img> parallax effect is declared by the following params inside its class:
            
            example: class="asset left-472 sp600 t120 z3"
            left-472 means left: -472px from the center
            sp600 is speed transition
            t120 is top to 120px
            z3 is z-index to 3
            Note: Maintain this order of params

            For the backgrounds, you can combine from the bgs folder :D
        -->
        <article class="slide" id="showcasing" style="background: url('{% static "content/img/backgrounds/landscape.png" %}') repeat-x top center;">
            <img class="asset left-30 sp600 t120 z1" src="{% static "content/img/slides/scene1/macbook.png" %}" />
            <div class="info">
                <h2>Dynamic worksheets.</h2>
                <h3>New exercises every time</h3>
            </div>
        </article>
        <article class="slide" id="ideas" style="background: url('{% static "content/img/backgrounds/aqua.jpg" %}') repeat-x top center;">
            <div class="info">
                <h2>Don't just learn Math. </h2>
                <h3>Become fluent in it.</h3>
            </div>
            <img class="asset left-480 sp600 t260 z1" src="{% static "content/img/slides/scene2/left.png" %}" />
            <img class="asset left-210 sp600 t213 z2" src="{% static "content/img/slides/scene2/middle.png" %}" />
            <img class="asset left60 sp600 t260 z1" src="{% static "content/img/slides/scene2/right.png" %}" />
        </article>
        <article class="slide" id="tour" style="background: url('{% static "content/img/backgrounds/color-splash.jpg" %}') repeat-x top center;">
            <img class="asset left-472 sp650 t210 z3" src="{% static "content/img/slides/scene3/ipad.png" %}" />
            <img class="asset left-365 sp600 t270 z4" src="{% static "content/img/slides/scene3/iphone.png" %}" />
            <img class="asset left-350 sp450 t135 z2" src="{% static "content/img/slides/scene3/desktop.png" %}" />
            <img class="asset left-185 sp550 t220 z1" src="{% static "content/img/slides/scene3/macbook.png" %}" />
            <div class="info">
                <h2>100% FREE. </h2>
                <h3>Built from parents to parents.</h3>
                <a href="/Addition/">START NOW</a>
            </div>
        </article>
	</section>
    <div id="showcase">
        <div class="container">
            <div class="section_header">
                <h3>Mathimize</h3>
            </div>            
            <div class="row feature_wrapper">
                <!-- Features Row -->
                <div class="features_op1_row">
                    <!-- Feature -->
                    <div class="col-md-4 feature first">
                        <div class="img_box">
                            <a href="/about">
                                <img src="{% static "content/img/service-dynamic.png" %}">
                                <span class="circle"> 
                                    <span class="plus">&#43;</span>
                                </span>
                            </a>
                        </div>
                        <div class="text">
                            <h6>Dynamic Worksheets</h6>
                            <p>
                                There are many worksheets out there, but all of them are static ones. You download them once and that's it. 
                            </p>
                            <p>At Mathimize, the worksheets are dynamic. You'll get a new one everytime you visit the site. Generate as many as you want.</p>
                        </div>
                    </div>
                    <!-- Feature -->
                    <div class="col-md-4 feature">
                        <div class="img_box">
                            <a href="/about">
                                <img src="{% static "content/img/service-math.png" %}">
                                <span class="circle"> 
                                    <span class="plus">&#43;</span>
                                </span>
                            </a>
                        </div>
                        <div class="text">
                            <h6>Become fluent in Math</h6>
                            <p>
                                Automatic recall of basic math facts (math fluency) is generally considered a key foundation for higher level math skills. Your kid can Add and Subtract. But how fast is he? Does he still use his fingers to do single digit operations? How fluent is he?
                            </p>
                        </div>
                    </div>
                    <!-- Feature -->
                    <div class="col-md-4 feature last">
                        <div class="img_box">
                            <a href="/about">
                                <img src="{% static "content/img/service-free.png" %}">
                                <span class="circle"> 
                                    <span class="plus">&#43;</span>
                                </span>
                            </a>
                        </div>
                        <div class="text">
                            <h6>100% FREE</h6>
                            <p>
                                I do Math drills with my kids every Sunday morning. The worksheets out there were static, so I wrote simple scripts that generated dynamic worksheets for my kids. I thought other parents would also appreciate these scripts, so I started Mathimize.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <!-- Scripts -->
    
    <script type="text/javascript" src="{% static "scripts/index-slider.js" %}"></script>	

{% endblock content %}

templates/login.html
{% extends "framed.html" %}
{% block framedcontent %}
    {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    <form method="post" action="{% url "django.contrib.auth.views.login" %}">
    {% csrf_token %}
    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>
    <input type="submit" value="login" />
    <input type="hidden" name="next" value="{{ next }}" />
    </form>
{% endblock %}